src/blueprints/flights/models.py
from .entities import Flight

def convert_from_file(file, flight_type):
    with open(file, 'r') as file:
        for line in file.readlines():
            time, callsign, airline, location, aircraft = line.split()[:5]
            try:
                flight = Flight.objects.get(callsign=callsign)
                flight.update(
                    time=time,
                    airline=airline,
                    location=location,
                    aircraft=aircraft,
                    route=' '.join(line.split()[5:]),
                    flight_type=flight_type
                )
            except Exception as crap:
                flight = Flight(
                    time=time,
                    callsign=callsign,
                    airline=airline,
                    location=location,
                    aircraft=aircraft,
                    route=' '.join(line.split()[5:]),
                    flight_type=flight_type
                )
                flight.save()

def init_from_file(file):
    with open(file, 'r') as file:
        for line in file.readlines():
            callsign, cid = line.split()
            flight = Flight.objects.get(callsign=callsign)
            book = {'cid':cid}
            flight.update(book=book)

src/models.py
from flask import render_template
from flask_mail import Message

class Mail(Message):
    @classmethod
    def for_email(cls, email, subj, tmpl, **tmpl_kwargs):
        _tmpl = tmpl if '.html' not in tmpl else tmpl[:-5]
        html_body = render_template(f'{tmpl}.html', **tmpl_kwargs)
        return cls(subj, [email], None, html_body)

    @classmethod
    def contactus(cls, email, username, subject, message, sender_mail):
        tmpl = 'mail/contactus'
        subj = f'{subject} - ContactUs'
        return cls.for_email(email, subj, tmpl, username=username, message=message, _email=sender_mail)
    
    @classmethod
    def flight_booked_to_user(cls, email, username, flight):
        tmpl = f'mail/user_flight_booked_{flight.flight_type}'
        subj = f'Porto RealOps - Departure slot confirmation'
        return cls.for_email(email, subj, tmpl, username=username, flight=flight)

    @classmethod
    def flight_booked_alert_staff(cls, user, flight):
        tmpl = f'mail/staff_flight_booked_{flight.flight_type}'
        subj = f'Porto RealOps - {flight.callsign} {flight.flight_type.capitalize()} slot booking'
        return cls.for_email('events@portugal-vacc.org', subj, tmpl, user=user, flight=flight)

src/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, StringField, TextAreaField, SubmitField
from wtforms.widgets import TextArea

class ContactUsForm(FlaskForm):
    sender_mail  = HiddenField('Sender Mail')
    sender_name  = HiddenField('Sender Name')
    subject      = StringField('Subject')
    message      = StringField(u'Text', widget=TextArea())
    save         = SubmitField('Send')

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.sender_mail.data = user.email
        self.sender_name.data = user.full_name


src/__init__.py
import os
from flask import Flask
from flask_login import LoginManager
from flask_bootstrap import Bootstrap
from flask_oauthlib.client import OAuth
from flask_mongoengine import MongoEngine
from flask_mail import Mail

from .config import configure_app
from .routes import configure_routes
from .blueprints.auth.models import build_oauth_args

def configure_extensions(app):
    _oauth = OAuth(app)
    app.oauth = _oauth.remote_app('lppr_realops', **build_oauth_args(app))

    Bootstrap().init_app(app)
    LoginManager().init_app(app)
    MongoEngine().init_app(app)

    mail = Mail()
    mail.init_app(app)
    app.mail = mail
    
def configure_blueprints(app):
    from src.blueprints import auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from src.blueprints import flights_bp
    app.register_blueprint(flights_bp, url_prefix='/flights')

def configure_hooks(app):
    from src.blueprints import tokengetter, user_loader
    app.oauth.tokengetter(tokengetter)
    app.login_manager.user_loader(user_loader)

    from src.blueprints.flights.models import convert_from_file, init_from_file

    # Initialization
    convert_from_file('src/static/store/arrs', 'arrival')
    convert_from_file('src/static/store/deps', 'departure')

    #init_from_file('src/static/store/init_deps')
    #init_from_file('src/static/store/init_arrs')

def create_app(app_name):
    app = Flask(app_name, template_folder='src/templates', static_folder='src/static')

    configure_app(app, os.environ.get('FLASK_ENV'))
    configure_extensions(app)
    configure_blueprints(app)
    configure_hooks(app)
    configure_routes(app)

    return app

src/blueprints/__init__.py
from .auth import bp as auth_bp, tokengetter, user_loader
from .flights import bp as flights_bp

src/blueprints/flights/__init__.py
from flask import Blueprint, render_template, redirect, url_for, current_app as app
from flask_login import login_required, current_user as user

from .entities import Flight
from ...models import Mail

bp = Blueprint('flights', __name__, template_folder='templates',
               static_folder='static')

@bp.route('/')
@login_required
def index():
    arrivals = Flight.objects(flight_type='arrival').order_by('time') 
    departures = Flight.objects(flight_type='departure').order_by('time') 
    return render_template('flights.html', arrivals=arrivals, departures=departures)

@bp.route('/<id>/book', methods=['POST'])
@login_required
def book(id):
    flight = Flight.get(id=id, book=None)
    if flight:
        book = {'cid': user.id}
        flight.update(book=book)

        user_mail = Mail.flight_booked_to_user(user.email, user.full_name, flight)
        staff_mail = Mail.flight_booked_alert_staff(user, flight)
        app.mail.send(user_mail)
        app.mail.send(staff_mail)

    return redirect(url_for('flights.index'))

@bp.route('/<id>/cancel_book')
@login_required
def cancel(id):
    flight = Flight.get(id=id, book__cid=user.id)
    if flight:
        flight.update(book=None)
    return redirect(url_for('flights.index'))

src/routes.py
from flask import redirect, url_for, render_template, request
from flask_login import login_required, current_user as user
from src.models import Mail
from .forms import ContactUsForm
from .blueprints.flights.entities import Flight

def configure_routes(app):
    @app.context_processor
    def main_args():
        return {
            'flights_booked': Flight.objects(book__cid=user.id),
        }

    @app.route('/')
    @login_required
    def index():
        perc_booked_deps = int(Flight.objects(
                book__ne=None, flight_type='departure').count() * 100 / \
            Flight.objects(flight_type='departure').count())
        perc_booked_arrs = int(Flight.objects(
                book__ne=None, flight_type='arrival').count() * 100 / \
            Flight.objects(flight_type='arrival').count())
        return render_template('index.html', perc_booked_deps=perc_booked_deps, perc_booked_arrs=perc_booked_arrs)

    @app.route('/contactus', methods=['POST', 'GET'])
    @login_required
    def contactus():
        senders = ['tmavicente@gmail.com', 'miguel.frias@portugal-vacc.org']
        form = ContactUsForm(user)
        if form.validate_on_submit():
            for s in senders:
                mail = Mail.contactus(
                    s, 
                    form.sender_name.data,
                    form.subject.data,
                    form.message.data,
                    form.sender_mail.data
                )
                app.mail.send(mail)
                return redirect(url_for('index'))
        return render_template('contactus.html', form=form)

    @app.errorhandler(401)
    def handle_401(error):
        return redirect(url_for('auth.login'))
    
    @app.errorhandler(400)
    def handle_400(error):
        return render_template('error.html', error=error)
    

src/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Porto RealOps{% endblock title %}

{% block styles %}
  {{super()}}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/realops.css') }}">
{% endblock styles %}

{% block scripts %}
  <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/current-day.js') }}"></script>
  {{super()}}
{% endblock scripts %}

<script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/current-day.js"></script>
{% block content %}
  <h1 class="text-center text-white d-none d-lg-block site-heading">
    <span class="text-primary site-heading-upper mb-3">Welcome to&nbsp;</span><span class="site-heading-lower">Porto Realops</span>
  </h1>
  <nav class="navbar navbar-light navbar-expand-lg bg-dark py-lg-4" id="mainNav">
    <div class="container"><a class="navbar-brand text-uppercase d-lg-none text-expanded" href="#">Porto REALOPS</a><button data-toggle="collapse" data-target="#navbarResponsive" class="navbar-toggler" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div
          class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="nav navbar-nav mx-auto">
              <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('index')}}">Home</a></li>
              <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('flights.index')}}">flights</a></li>
              <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('contactus')}}">Contact us</a></li>
          </ul>
      </div>
    </div>
  </nav>
  {% if flights_booked %}
  <div class="alert alert-secondary" role="alert">
    <h6>My booked flights:</h6>
    <ul>
      {% for b in flights_booked %}
      <li style="list-style-type: none; padding:15px;">{{b.callsign}}, {{b.flight_type}} at {{b.time}}z {% if b.flight_type == 'departure' %}to{% else %}from{% endif %} {{b.location}} 
        <span style="float:right; margin-right:25px"><a href="{{url_for('flights.cancel', id=b.id) }}" type="button" class="btn btn-danger btn-sm">Cancel Flight {{b.callsign}}</a></span>
      </li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}
  {% block page_content %}
          
  {% endblock page_content %}
  <footer class="footer text-faded text-center py-5" style="background-color: rgba(15,30,47,0.73);">
    <div class="container">
        <p class="m-0 small">Copyright&nbsp;©&nbsp;Portugal vACC 2021</p>
    </div>
  </footer>
{% endblock content %}

src/templates/contactus.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block page_content %}
<section class="page-section about-heading">
    <div class="container">
        <div class="about-heading-content">
            <div class="row">
                <div class="col-lg-10 col-xl-9 mx-auto">
                    <div class="bg-faded rounded p-5" style="margin-top: 75px;">
                        <h2 class="section-heading mb-4"><span class="section-heading-upper">Contact Us</span></h2>
                        {{ wtf.quick_form(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock page_content %}

src/templates/error.html
{% extends "base.html" %}

{% block page_content %}
<section class="page-section about-heading">
    <div class="container">
        <div class="about-heading-content">
            <div class="row">
                <div class="col-lg-10 col-xl-9 mx-auto">
                    <div class="bg-faded rounded p-5" style="margin-top: 75px;">
                        <h2 class="section-heading mb-4"><span class="section-heading-upper">Error</span></h2>
                        {{error}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock page_content %}

src/templates/flights.html
{% extends "base.html" %}

{% block scripts %}
{{super()}}
<script>
    function computeFlight(e){
        e = JSON.parse(e)
        document.getElementById("modal-body").innerHTML = '<center><img width="50%" src="https://porto-realops.portugal-vacc.org/static/logos/'+e.airline+'.png"></center><br>\
            <code>\
                Callsign<span style="float:right">' + e.callsign + '</span><br> \
                Aircraft<span style="float:right">' + e.aircraft + '</span><br> \
                Route<span style="float:right">' + e.route + '</span><br> \
            </code>'
        let _id = e._id['$oid']
        document.getElementById('bookFlightForm').action = './' + _id + '/book' 
    }
</script>
{% endblock scripts %}

{% block page_content %}
<section class="page-section about-heading">
    <div class="container">
        <div class="about-heading-content">
            <div class="row">
                <div class="col-lg-10 col-xl-9 mx-auto">
                    <div id="content_deps" class="bg-faded rounded p-5">
                        <h2 class="section-heading mb-4"><span class="section-heading-upper">Current Departures</span></h2>
                        <div class="table-responsive text-center">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Dep. Time (UTC)</th>
                                        <th><strong>Flight no</strong></th>
                                        <th><strong>Aircraft</strong><br></th>
                                        <th>Airline</th>
                                        <th>Destination</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for departure in departures %}
                                    <tr>
                                        <td>{{departure.time}}<br></td>
                                        <td>{{departure.callsign}}<br></td>
                                        <td>{{departure.aircraft}}</td>
                                        <td  width="55%"><img width="50%" src="{{url_for('static', filename='logos/'+departure.airline+'.png')}}"></td>
                                        <td>{{departure.location}}<br></td>
                                        {% if not departure.book %}
                                        <td><a type="button" href="#" onclick="return computeFlight('{{departure.to_json()}}')" data-toggle="modal" data-target="#bookFlightModal" class="btn btn-primary btn-sm">Book</a></td>
                                        {% elif departure.book %}
                                        <td width="100%">Booked by {{departure.book.cid}}</td>
                                        {% else %}
                                        <td></td>
                                        {% endif %}
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div id="content_arrs" class="bg-faded rounded p-5">
                        <h2 class="section-heading mb-4"><span class="section-heading-upper">Current Arrivals</span></h2>
                        <div class="table-responsive text-center">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Arr. Time (UTC)</th>
                                        <th><strong>Flight no</strong></th>
                                        <th><strong>Aircraft</strong><br></th>
                                        <th>Airline</th>
                                        <th>From</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for arrival in arrivals %}
                                    <tr>
                                        <td>{{arrival.time}}<br></td>
                                        <td>{{arrival.callsign}}<br></td>
                                        <td>{{arrival.aircraft}}</td>
                                        <td width="55%"><img width="50%" src="{{url_for('static', filename='logos/'+arrival.airline+'.png')}}"></td>
                                        <td>{{arrival.location}}<br></td>
                                        {% if not arrival.book %}
                                        <td><a type="button" href="#" onclick="return computeFlight('{{arrival.to_json()}}')" data-toggle="modal" data-target="#bookFlightModal" class="btn btn-primary btn-sm">Book</a></td>
                                        {% elif arrival.book %}
                                        <td width="100%">Booked by {{arrival.book.cid}}</td>
                                        {% else %}
                                        <td></td>
                                        {% endif %}
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Book Flight Form -->
<div id="bookFlightModal" class="modal fade" role="dialog">
    <form id="bookFlightForm" method="POST">
        <div class="modal-dialog">
    
        <!--  Book Flight Form content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="modal-title" class="modal-title">Book Flight</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
            <p id="modal-body">Some text in the modal.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-success">Book</button>
            </div>
        </div>
    
        </div>
    </form>
</div>
{% endblock page_content %}

src/templates/index.html
{% extends "base.html" %}

{% block page_content %}
  <section class="page-section clearfix">
      <div class="container">
          <div class="intro"><img class="img-fluid intro-img mb-3 mb-lg-0 rounded" src="{{ url_for('static', filename='img/intro.png') }}" style="width: 586px;">
              <div class="intro-text left-0 text-centerfaded p-5 rounded bg-faded text-center" style="width: 499px;height: 444px;">
                  <h2 class="section-heading mb-4"><span class="section-heading-upper"><strong>Sunday 11th&nbsp;April 2021</strong><br></span><span class="section-heading-lower"><strong>1400Z-1900Z</strong><br></span></h2>
                  <p class="mb-3"><strong>Porto Real Ops 2021</strong>&nbsp;is the second edition of one of Portugal's largest events. It's the coming together of some of VATSIM's finest pilots and controllers with an amazing scenery in the background.&nbsp;<br><br></p>
                  <div id="deparrs_row" class="row">
                      <div id="departures">
                          <p>Departures</p>
                          <div class="progress" id="deps_progress">
                              <div class="progress-bar" aria-valuenow="{{perc_booked_deps}}" aria-valuemin="0" aria-valuemax="100" style="width: {{perc_booked_deps}}%;">{{perc_booked_deps}}%</div>
                          </div>
                      </div>
                      <div id="arrivals">
                          <p>Arrivals</p>
                          <div class="progress">
                              <div class="progress-bar" aria-valuenow="{{perc_booked_arrs}}" aria-valuemin="0" aria-valuemax="100" style="width: {{perc_booked_arrs}}%;">{{perc_booked_arrs}}%</div>
                          </div>
                      </div>
                  </div>
                  <div class="mx-auto intro-button"><a class="btn btn-primary d-inline-block mx-auto btn-xl" role="button" href="{{url_for('flights.index')}}">Check our flights!</a></div>
              </div>
          </div>
      </div>
  </section>
  <section class="page-section cta" style="padding: 150px 0px;background-color: rgba(98,86,230,0.01);height: 595px;">
      <div class="container">
          <div class="row">
              <div class="col-xl-9 mx-auto">
                  <div class="cta-inner text-center rounded">
                      <h2 class="section-heading mb-4"><span class="section-heading-upper">Our Promise</span><span class="section-heading-lower">To You</span></h2>
                      <p class="mb-0">Porto Airport is known for its approach over Douro River and a set of 6 bridges over the river within a 5 km extension.On Sunday 11th&nbsp;April, pilots from all over the world are invited to choose from one of the&nbsp;84 flights on offer:&nbsp;<strong>44 arrivals</strong>&nbsp;and&nbsp;<strong>40 departures</strong>.<br></p>
                  </div>
              </div>
          </div>
      </div>
  </section>    
{% endblock page_content %}